
GET http://localhost:3017/api/energy_drinks

###

POST http://localhost:3017/api/energy_drink HTTP/1.1
content-type: application/json

{
    "drink_id": 3,
    "day_id": 8
}

###

GET http://localhost:3017/api/energy_drinks/day?week_day_id=3




